### ISSUE TITLE
Add permissions to configure search filter in Kowl business

### ISSUE THREAD

**Issue by weeco** [cloudhut/kowl#88]
Operators may want to prevent the usage of search filters. Therefore the usage of search filters should be a configurable action.

**TODO**

- [x] Add action to allow search filters in Kowl Business (backend)
- [x] Add endpoint which tells whether the user is allowed to use JS filters for a given topic (backend)
- [ ] Disable filters in frontend if user is not allowed to use them (frontend)
